// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJPO_JLZsq6ri9TSuWFIyuu3P1Q2nzwT8',
    appId: '1:809776981244:web:5a6599ba24919779ffa379',
    messagingSenderId: '809776981244',
    projectId: 'myfirstapp-424ab',
    authDomain: 'myfirstapp-424ab.firebaseapp.com',
    storageBucket: 'myfirstapp-424ab.appspot.com',
    measurementId: 'G-34QCBJLND8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBBW0Carht5jEGONj7z0Beilfq88IlVQc',
    appId: '1:809776981244:android:f6ca679704365ec4ffa379',
    messagingSenderId: '809776981244',
    projectId: 'myfirstapp-424ab',
    storageBucket: 'myfirstapp-424ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCSQjPIa9ZinL6Llxq-1mSqSoldvtxH2s',
    appId: '1:809776981244:ios:e40cdb795ac13240ffa379',
    messagingSenderId: '809776981244',
    projectId: 'myfirstapp-424ab',
    storageBucket: 'myfirstapp-424ab.appspot.com',
    iosClientId: '809776981244-06dqhpg5553if1t4h5dt3785ldb76m5m.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMyNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCSQjPIa9ZinL6Llxq-1mSqSoldvtxH2s',
    appId: '1:809776981244:ios:e40cdb795ac13240ffa379',
    messagingSenderId: '809776981244',
    projectId: 'myfirstapp-424ab',
    storageBucket: 'myfirstapp-424ab.appspot.com',
    iosClientId: '809776981244-06dqhpg5553if1t4h5dt3785ldb76m5m.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMyNotes',
  );
}
